### PR TITLE
Handling events API similar to jQuery

### PR DESCRIPTION
**Pull request by gabrielrios**
So, in the way of making this looks more like Ruby and less JS I want to propose this Event Handling API.

On Phaser.js when we want to track a event directly we do something like this:
```javascript
var callback = function() {
  console.log("event down")
}
sprite.events.onInputDown.add(callback, this)
```

I think this is weird, and to be honest cascading objects like this doesn't feel right to me. So I came up with:

```ruby
sprite.events.on(:down) do 
  puts "event down"
end
```

Or on a more complex case:

```ruby
class Player
  def create
     @sprite = game.add.sprite(x, y, sprite_key)
     @sprite.events.on(:down, self, &method(:down))
  end

  private
  def down
    puts "event down"
  end
end
```

To me this seems a better API, want some inputs on it. @ylluminarious

### CODE REVIEW

**Comment by ylluminarious** [comment]
@gabrielrios This does seem to be a more Ruby-like API, so I'm pretty fine with what you've done here. Have you tested it out and made sure it works alright?

**Comment by gabrielrios** [comment]
I haven't tested much, but I have a project here using this branch already and things seems ok.

**Comment by gabrielrios** [comment]
@andreanastacio @ylluminate if you have time and I'd like your opinion on this.

**Comment by ylluminate** [comment]
I think you made a good call here @gabrielrios.

**Pull request merged**
